// games-data.js
window.gamesDataset = [
  {
    "id": "shellshock",
    "title": "Shellshock.io",
    "url": "https://shellshock.io",
    "category": "multiplayer",
    "safetyRating": "red",
    "desc": "First person shooter using egg-cellent weaponry and customizable eggs.",
    "safetyProfile": "Public matchmaking places children into live text and voice chats with anonymous players. Parents must click 'Create Private Game' on the main menu to build an isolated room for classmates.",
    "players": "20 Players Max",
    "violence": "cartoon",
    "chat": "public",
    "tags": ["Shooter", "Eggs", "3D"],
    "emoji": "🥚"
  },
  {
    "id": "stumbleguys",
    "title": "Stumble Guys",
    "url": "https://stumbleguys.com",
    "category": "multiplayer",
    "safetyRating": "yellow",
    "desc": "Run, dash, and slide past obstacles in this massively multiplayer knockout party game.",
    "safetyProfile": "No in-game keyboard or voice chat, eliminating unmoderated social risks. Free-to-play page contains rotating ad networks. Ad-blocker recommended.",
    "players": "32 Players Max",
    "violence": "none",
    "chat": "none",
    "tags": ["Party", "Physics", "Survival"],
    "emoji": "🏃"
  },
  {
    "id": "smashkarts",
    "title": "SmashKarts",
    "url": "https://smashkarts.io",
                    "category": "multiplayer",
                    "safetyRating": "yellow",
                    "desc": "Fast-paced online multiplayer go-kart battle game in beautiful arenas.",
                    "safetyProfile": "No custom keyboard chat features are available in standard browser play, eliminating social risks. The host website runs programmatic banner ads; an ad-blocker is recommended.",
                    "players": "8 Players Max",
                    "violence": "cartoon",
                    "chat": "none",
                    "tags": ["Battle Arena", "Karts", "Combat"],
                    "emoji": "🛒"
          },
          {
                    "id": "minecraft",
                    "title": "Classic Minecraft",
                    "url": "https://classic.minecraft.net/",
                    "category": "1player",
                    "safetyRating": "green",
                    "desc": "Play the original creative block builder straight in your browser window.",
                    "safetyProfile": "No public servers, tracking, or ad placements. Single-player by default; multiplayer only functions if private link codes are manually generated.",
                    "players": "Single Player",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Creative Sandbox", "Building", "Blocks"],
                    "emoji": "⛏️"
          },
          {
                    "id": "nealfun",
                    "title": "Neal.fun",
                    "url": "https://neal.fun",
                    "category": "learning",
                    "safetyRating": "green",
                    "desc": "An incredible vault of dynamic scientific experiments, quizzes, and cool curiosities.",
                    "safetyProfile": "Entirely ad-free, secure, and self-contained. Safely open for unattended and self-paced study play.",
                    "players": "Single Player",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Cyber Science", "Science Sandbox", "Interactive"],
                    "emoji": "🧪"
          },
          {
                    "id": "dinosaurgame",
                    "title": "Dinosaur Game",
                    "url": "https://offline-dino-game.firebaseapp.com/",
                    "category": "clicker",
                    "safetyRating": "green",
                    "desc": "Help T-Rex leap over cactus obstacles and pterodactyls in this browser classic.",
                    "safetyProfile": "Self-hosted, ad-free standalone browser game. No social chat mechanics or network tracking.",
                    "players": "Single Player",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Chrome Classic", "Endless Run", "Offline Game"],
                    "emoji": "🦖"
          },
          {
                    "id": "twovstwo",
                    "title": "2v2.io",
                    "url": "https://2v2.io/",
                    "category": "multiplayer",
                    "safetyRating": "red",
                    "desc": "Fast-paced building and shooting 2v2 tactical arena. Team up with a classmate to out-build and defeat your opponents.",
                    "safetyProfile": "Requires private lobbies to bypass standard unmoderated matchmaking servers and stranger risk.",
                    "players": "4 Players Max",
                    "violence": "cartoon",
                    "chat": "none",
                    "tags": ["Shooter", "Building", "Tactical"],
                    "emoji": "⚔️"
          },
          {
                    "id": "kartbros",
                    "title": "Kartbros",
                    "url": "https://kartbros.io/",
                    "category": "multiplayer",
                    "safetyRating": "yellow",
                    "desc": "Speed through vibrant tracks and complete races with up to 8 racers online.",
                    "safetyProfile": "No in-game text or voice communication, eliminating unmoderated stranger hazards. The host page runs display ads; ad-blocker recommended.",
                    "players": "8 Players Max",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Racing", "Karting", "Action"],
                    "emoji": "🏎️"
          },
          {
                    "id": "buildnowgg",
                    "title": "BuildNow GG",
                    "url": "https://www.crazygames.com/game/buildnow-gg",
                    "category": "multiplayer",
                    "safetyRating": "red",
                    "desc": "An intense 3D building and shooting battle arena game. Replaced 1v1.lol.",
                    "safetyProfile": "Requires setting up private custom keys. Public matchmaking contains unmoderated chat risk.",
                    "players": "8 Players Max",
                    "violence": "cartoon",
                    "chat": "public",
                    "tags": ["Fortnite Alt", "Building", "Survival"],
                    "emoji": "⛏️"
          },
          {
                    "id": "wrestlebros",
                    "title": "Wrestle Bros",
                    "url": "https://freegames.io/game/wrestle-bros",
                    "category": "multiplayer",
                    "safetyRating": "yellow",
                    "desc": "A hilarious browser physics wrestling game. Smash buttons, perform wild jumps, and slam your classmates!",
                    "safetyProfile": "Safe, zero-chat wrestling play. Contains startup ad placements. Ad-blocker recommended.",
                    "players": "8 Players Max",
                    "violence": "cartoon",
                    "chat": "none",
                    "tags": ["Wrestling", "Combat", "Sports"],
                    "emoji": "🤼"
          },
          {
                    "id": "badegg",
                    "title": "Bad Egg",
                    "url": "https://freegames.io/game/bad-egg",
                    "category": "1player",
                    "safetyRating": "yellow",
                    "desc": "Survive waves of zombie eggs as a heavily armed egg in this intense battle arena.",
                    "safetyProfile": "Single-player only with no social features. Contains standard pre-roll video ads.",
                    "players": "8 Players Max",
                    "violence": "cartoon",
                    "chat": "none",
                    "tags": ["Shooter", "Survival", "Zombies"],
                    "emoji": "🍳"
          },
          {
                    "id": "soccerbros",
                    "title": "Soccer Bros",
                    "url": "https://freegames.io/game/soccer-bros",
                    "category": "multiplayer",
                    "safetyRating": "yellow",
                    "desc": "Fast-paced browser soccer game. Dribble, pass, tackle, and shoot to score goals against your classmates!",
                    "safetyProfile": "No built-in chat mechanics. Ad-blocker filters background ad banner placements.",
                    "players": "8 Players Max",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Sports", "Soccer", "Fun"],
                    "emoji": "⚽"
          },
          {
                    "id": "baseballbros",
                    "title": "Baseball Bros",
                    "url": "https://freegames.io/game/baseball-bros",
                    "category": "multiplayer",
                    "safetyRating": "yellow",
                    "desc": "A highly competitive browser baseball game. Pitch, swing, and hit home runs against your friends!",
                    "safetyProfile": "Ad rotations active on host site loader. Zero communication features inside play.",
                    "players": "2 Players Max",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Sports", "Baseball", "PvP"],
                    "emoji": "⚾"
          },
          {
                    "id": "footballbros",
                    "title": "Football Bros",
                    "url": "https://freegames.io/game/football-bros",
                    "category": "multiplayer",
                    "safetyRating": "yellow",
                    "desc": "An exciting browser American football game. Throw passes, execute tackles, and score touchdowns with simple controls!",
                    "safetyProfile": "Features startup ad-loaders. No multiplayer chat risk. uBlock Origin recommended.",
                    "players": "8 Players Max",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Sports", "Football", "Fun"],
                    "emoji": "🏈"
          },
          {
                    "id": "skribbl",
                    "title": "Skribbl.io",
                    "url": "https://skribbl.io",
                    "category": "multiplayer",
                    "safetyRating": "red",
                    "desc": "A fun and highly educational guess-the-word drawing board game.",
                    "safetyProfile": "Public lobbies contain unmoderated typed chat. Always play in private, secure password lobbies.",
                    "players": "20 Players Max",
                    "violence": "none",
                    "chat": "public",
                    "tags": ["Drawing", "Word Guessing", "Party"],
                    "emoji": "✏️"
          },
          {
                    "id": "garticphone",
                    "title": "Gartic Phone",
                    "url": "https://garticphone.com/",
                    "category": "multiplayer",
                    "safetyRating": "red",
                    "desc": "The ultimate drawing telephone game. Draw, prompt, and laugh with friends.",
                    "safetyProfile": "Only play with trusted classmates. Public rooms can feature inappropriate prompt submissions.",
                    "players": "2-30 Players",
                    "violence": "none",
                    "chat": "public",
                    "tags": ["Drawing", "Party Game", "Creative"],
                    "emoji": "🎨"
          },
          {
                    "id": "retrobowl",
                    "title": "Retro Bowl",
                    "url": "https://retrobowl.me/",
                    "category": "multiplayer",
                    "safetyRating": "yellow",
                    "desc": "A gorgeous classic 8-bit American football manager simulator. Draft, trade, and win!",
                    "safetyProfile": "Features standard host banner advertisements. No built-in chat mechanisms.",
                    "players": "1-2 Players",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Sports", "Management", "Retro Grid"],
                    "emoji": "🏈"
          },
          {
                    "id": "slither",
                    "title": "Slither.io",
                    "url": "https://slither.io",
                    "category": "1player",
                    "safetyRating": "yellow",
                    "desc": "Grow your snake by eating glowing orbs. Simple mouse control, no keyboard needed.",
                    "safetyProfile": "No chat boxes. Contains localized skin advertising boxes on loading. uBlock filters these.",
                    "players": "Single Player",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Snake", "Casual", "No Keyboard"],
                    "emoji": "🐍"
          },
          {
                    "id": "flappybird",
                    "title": "Flappy Bird",
                    "url": "https://flappy-bird-web.appspot.com/",
                    "category": "clicker",
                    "safetyRating": "green",
                    "desc": "Navigate the classic flapping bird safely through green pipeline obstacles.",
                    "safetyProfile": "Entirely ad-free, self-contained single-player setup. Safe for immediate, unattended play.",
                    "players": "Single Player",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Retro Classic", "Hard Mode", "Arcade"],
                    "emoji": "🐦"
          },
          {
                    "id": "spacebarclicker",
                    "title": "Spacebar Clicker",
                    "url": "https://js13kgames.com/games/spacebar-clicker/index.html",
                    "category": "clicker",
                    "safetyRating": "green",
                    "desc": "Challenge your raw muscle memory and test how fast you can tap spacebar.",
                    "safetyProfile": "Self-hosted, static single-page setup. Completely ad-free, chat-free, and tracker-free.",
                    "players": "Single Player",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Reaction", "Clicker", "Minigame"],
                    "emoji": "⌨️"
          },
          {
                    "id": "spaceinvaders",
                    "title": "Space Invaders",
                    "url": "http://www.eugenestarr.com/space-invaders.html",
                    "category": "1player",
                    "safetyRating": "green",
                    "desc": "Command your arcade spaceship and defend the planet against incoming aliens.",
                    "safetyProfile": "Ad-free custom HTML5 canvas build. Completely safe for instant, independent play.",
                    "players": "Single Player",
                    "violence": "cartoon",
                    "chat": "none",
                    "tags": ["Retro Classic", "Shooter", "Vintage"],
                    "emoji": "👾"
          },
          {
                    "id": "pacman",
                    "title": "Pac-Man",
                    "url": "https://www.google.com/logos/2010/pacman10-i.html",
                    "category": "1player",
                    "safetyRating": "green",
                    "desc": "Feed on dots and dodge retro colorful ghosts in the famous Google Doodle maze.",
                    "safetyProfile": "Self-contained Google archive. Completely ad-free, chat-free, and safe for all ages.",
                    "players": "Single Player",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Arcade Classic", "Maze", "Doodle"],
                    "emoji": "🍋"
          },
          {
                    "id": "run3",
                    "title": "Run 3",
                    "url": "https://run3.io/",
                    "category": "1player",
                    "safetyRating": "yellow",
                    "desc": "Defy gravity and jump over crumbling space tiles in a futuristic 3D cosmic highway.",
                    "safetyProfile": "No communication risks. Contains startup loading screen ads. uBlock recommended.",
                    "players": "Single Player",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Cosmic Runner", "Gravity Shift", "3D"],
                    "emoji": "🌌"
          },
          {
                    "id": "townscaper",
                    "title": "Townscaper",
                    "url": "https://oskarstalberg.com/Townscaper/",
                    "category": "learning",
                    "safetyRating": "green",
                    "desc": "Instantly build beautiful floating sea towns block by block. Beautiful design toy.",
                    "safetyProfile": "Entirely ad-free, creative architectural sandbox toy with zero social chat features.",
                    "players": "Single Player",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Architectural Toy", "Artistic", "Sandbox"],
                    "emoji": "⛵"
          },
          {
                    "id": "linerider",
                    "title": "Line Rider",
                    "url": "https://linerider.com",
                    "category": "learning",
                    "safetyRating": "yellow",
                    "desc": "Draw tracks and use interactive physics to guide your sledding rider smoothly.",
                    "safetyProfile": "No social chat risks. Background sidebar ad banners recommend an active ad-blocker.",
                    "players": "Single Player",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Physics Simulation", "Creative Canvas"],
                    "emoji": "🛹"
          },
          {
                    "id": "wordle",
                    "title": "Wordle",
                    "url": "https://www.nytimes.com/games/wordle/index.html",
                    "category": "learning",
                    "safetyRating": "yellow",
                    "desc": "Solve the daily five-letter word puzzle using smart logic and process of elimination.",
                    "safetyProfile": "NYT hosted. No chat risks; minimal static page tracking cookies. safe and secure.",
                    "players": "Single Player",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Vocabulary", "Daily Puzzle", "Logic"],
                    "emoji": "📝"
          },
          {
                    "id": "quickdraw",
                    "title": "Quick, Draw!",
                    "url": "https://quickdraw.withgoogle.com/",
                    "category": "learning",
                    "safetyRating": "green",
                    "desc": "Doodle prompts in under 20 seconds and see if Google's friendly neural network guesses it.",
                    "safetyProfile": "Google AI experimental educational sandbox. Ad-free, secure, and safe for classroom play.",
                    "players": "Single Player",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Artificial Intelligence", "Sketching", "Educational"],
                    "emoji": "🧠"
          },
          {
                    "id": "littlealchemy",
                    "title": "Little Alchemy 2",
                    "url": "https://littlealchemy2.com/",
                    "category": "learning",
                    "safetyRating": "yellow",
                    "desc": "Synthesize and construct elements from scratch starting with fire, water, earth, and air.",
                    "safetyProfile": "Non-competitive educational chemistry puzzle. Ad-blocker recommended to filter page ads.",
                    "players": "Single Player",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Chemistry Puzzle", "Science Lab", "Logic"],
                    "emoji": "⚗️"
          },
          {
                    "id": "supermario",
                    "title": "Super Mario",
                    "url": "https://supermarioplay.com/fullscreen",
                    "category": "1player",
                    "safetyRating": "yellow",
                    "desc": "Jump, run, collect gold coins, and rescue Princess Peach in this NES classic.",
                    "safetyProfile": "Contains retro website ad banners. safe keyboard platformer controls with ad blocker.",
                    "players": "Single Player",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Nintendo Classic", "Platformer", "Retro"],
                    "emoji": "🍄"
          },
          {
                    "id": "geometrydash",
                    "title": "Geometry Dash",
                    "url": "https://www.geometrydash.com/",
                    "category": "1player",
                    "safetyRating": "yellow",
                    "desc": "Rhythm-based platformer. Dodge dangerous spikes and obstacles to upbeat music.",
                    "safetyProfile": "Ad widgets active on startup loader. Zero social chat integration.",
                    "players": "Single Player",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Rhythm", "Music Platformer", "Skill"],
                    "emoji": "📐"
          },
          {
                    "id": "jellymario",
                    "title": "Jelly Mario",
                    "url": "https://jellymar.io/",
                    "category": "1player",
                    "safetyRating": "green",
                    "desc": "Super Mario but everything—from Mario to the enemies—behaves like dynamic jelly.",
                    "safetyProfile": "Ad-free classic physics sandbox toy. safe, clean single-player play.",
                    "players": "Single Player",
                    "violence": "none",
                    "chat": "none",
                    "tags": ["Physics Sandbox", "Absurd", "Humorous"],
                    "emoji": "🍮"
          }
];
